# Data Programming in Python | BAIS:6040
# Homework 3. Functions, Exceptions, and Numpy

## Instructions

To complete the homework, fill in the commands needed to finish all of the exercises below. Program everything inside this notebook. If the exercises request that you store information within certain variables, please use those specific variables names (case sensitive).

## Exercises

1\. Write a function <i>get_all_stats</i> that takes a list <i>l</i> of float pointing numbers as an argument and returns a tuple of the min, max, sum, and average of all \*positive\* numbers in <i>l</i>. (Hint: you may need a temporary list inside the function body to store the positive numbers in <i>l</i>.) (15 pts)

In [1]:
# YOUR CODE HERE
def get_all_stats(l):
    positive_list = list(filter(lambda x: x>-1,l ))
    if len(positive_list)>0:
        _min=positive_list[0]
        _max=positive_list[0]
        _sum=0
        for item in positive_list:
            if item >= _max:
                _max=item
            if item <= _min:
                _min=item
            _sum+=item
        return _min, _max, _sum, _sum/len(positive_list)
    else:
        return 0,0,0,0

In [2]:
# Test the function here
get_all_stats([1.0, 2.0, 3.0])          # Output: (1.0, 3.0, 6.0, 2.0).

(1.0, 3.0, 6.0, 2.0)

In [3]:
# Test the function here
get_all_stats([1.0, 2.0, 3.0, -1.0])    # Output: (1.0, 3.0, 6.0, 2.0).

(1.0, 3.0, 6.0, 2.0)

2\. Write a function <i>get_all_stats2</i> that works the same as <i>get_all_stats</i> above. In addition, it returns "Invalid value!" if <i>l</i> has any non-floating point number. (5 pts)

In [4]:
# YOUR CODE HERE
def get_all_stats2(l):
    non_float_list = list(filter(lambda x: type(x)!=float,l ))
    if len(non_float_list)>0:
        return "Invalid value!"
    else:
        return get_all_stats(l)

In [5]:
# Test the function here
get_all_stats2([1.0, 2.0, 3.0, -1.0])    # Output: (1.0, 3.0, 6.0, 2.0).

(1.0, 3.0, 6.0, 2.0)

In [6]:
# Test the function here
get_all_stats2([1.0, 2.0, 3, -1.0])      # Output: 'Invalid value!'.

'Invalid value!'

3\. Write a function <i>truncate</i> that takes a string <i>s</i> and an integer <i>limit</i> as arguments and returns the string as it is if the length of the string is equal to or less than <i>limit</i>. If the length is greater than <i>limit</i>, it only takes the <i>limit</i>-length leading substring of <i>s</i> (i.e., from the index position 0 to <i>limit</i> -1) replacing the rest of <i>s</i> with "..." and return that truncated string. Set the default value of <i>limit</i> to 50. (15 pts)

In [7]:
# YOUR CODE HERE
def truncate(s, limit=50):
    if len(s)<=limit:
        return s;
    elif len(s)>limit:
        return "{}...".format(s[:limit])
    else:
        return "Limit should be a positive number!"

In [8]:
# Test the function here
truncate("This homework corresponds to the Jun 4 class.", 50)
# Output: 'This homework corresponds to the Jun 4 class.'.

'This homework corresponds to the Jun 4 class.'

In [9]:
# Test the function here
truncate("This homework corresponds to the Jun 4 class. Please refer to the corresponding lecture materials posted on ICON.")
# Output: 'This homework corresponds to the Jun 4 class. Plea...'.

'This homework corresponds to the Jun 4 class. Plea...'

4\. Create a dictionary <i>kwargs</i> that sets the parameter values of <i>s</i> and <i>limit</i> on your own and call the function <i>truncate</i> by passing <i>kwargs</i>. (5 pts)

In [10]:
# YOUR CODE HERE
kwargs = {"s": "This homework corresponds to the Jun 4 class.", "limit": 50}
truncate(**kwargs)

'This homework corresponds to the Jun 4 class.'

5\. Given the definintions of r and s below, add the two arrays together using vectorization.
(10 pts)

In [11]:
# run this cell first
import numpy as np

np.random.seed(0)
r = np.arange(12).reshape((4,3))
s = np.arange(12).reshape((4,3))*0.5

In [12]:
# YOUR CODE HERE
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

6\. Create a 10 x 10 array <i>x</i> of random integers between 1 (inclusive) and 100 (inclusive). (10 pts)

In [13]:
# YOUR CODE HERE
x=np.random.randint(1,100,(10,10))

In [14]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
x

array([[45, 48, 65, 68, 68, 10, 84, 22, 37, 88],
       [71, 89, 89, 13, 59, 66, 40, 88, 47, 89],
       [82, 38, 26, 78, 73, 10, 21, 81, 70, 80],
       [48, 65, 83, 89, 50, 30, 20, 20, 15, 40],
       [33, 66, 10, 58, 33, 32, 75, 24, 36, 76],
       [56, 29, 35,  1,  1, 37, 54,  6, 39, 18],
       [80,  5, 43, 59, 32,  2, 66, 42, 58, 36],
       [12, 47, 83, 92,  1, 15, 54, 13, 43, 85],
       [76, 69,  7, 69, 48,  4, 77, 53, 79, 16],
       [21, 59, 24, 80, 14, 86, 49, 50, 70, 42]])

7\. Create a 10 x 10 array <i>y</i> of integers from 100 (inclusive) to 1 (inclusive). Order is important. For example, the first row has integers from 100 to 91, the second row from 90 to 81, and so on and so forth. (10 pts)

In [15]:
# YOUR CODE HERE
z=np.arange(1, 101).reshape(10,10)[::-1]
y=np.empty((10,10),int)
for row in range(len(z)):
    y[row] = z[row][::-1]

In [16]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
y

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

8\. Get all the values that are in the first 5 rows and the last 5 columns of <i>x</i> and assign the resulting array to <i>x_top_right</i>. Get all the values that are in the last 5 rows and the first 5 columns of <i>y</i> and assign the resulting array to <i>y_bottom_left</i>. (10 pts)

In [17]:
# YOUR CODE HERE
x_top_right = x[:5,-5:]
y_bottom_left = y[-5:,:5]

In [18]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
x_top_right, y_bottom_left

(array([[10, 84, 22, 37, 88],
        [66, 40, 88, 47, 89],
        [10, 21, 81, 70, 80],
        [30, 20, 20, 15, 40],
        [32, 75, 24, 36, 76]]),
 array([[50, 49, 48, 47, 46],
        [40, 39, 38, 37, 36],
        [30, 29, 28, 27, 26],
        [20, 19, 18, 17, 16],
        [10,  9,  8,  7,  6]]))

9\. Before we calculate the dot product of <i>x_top_right</i> and <i>y_bottom_left</i>, check if the number of columns of <i>x_top_right</i> equals the number of rows of <i>y_bottom_left</i>, using an <b>assert</b> statement. Do not directly put their numbers (i.e., 5) in the test. (Hint: if the <b>assert</b> statement returns an AssertionError, that means you had wrong <i>x_top_right</i> or <i>y_bottom_left</i>.) (10 pts)

In [19]:
# YOUR CODE HERE
assert x_top_right.shape[1] == y_bottom_left.shape[0], "Dot product cannot be calculated"

10\. Get the dot product of <i>x_top_right</i> and <i>y_bottom_left</i>. (10 pts)

In [20]:
# YOUR CODE HERE
np.dot(x_top_right, y_bottom_left)  

array([[6140, 5899, 5658, 5417, 5176],
       [9370, 9040, 8710, 8380, 8050],
       [5970, 5708, 5446, 5184, 4922],
       [3600, 3475, 3350, 3225, 3100],
       [6800, 6557, 6314, 6071, 5828]])